version: 0
verbose: false
mounts: # mount configurations Available keys: NOW, UUID,
- !mounts.SSHCode &code_mount
  local_path: .
  # host_path: $JYNMNT/latent-planning/latent-planning
  local_tar: /tmp/{now:%Y-%m-%d}/{now:%H%M%S.%f}-jaynes-demo.tar
  host_path: "{secret.JYNS_HOME}/jaynes-demo/{now:%Y-%m-%d}/{now:%H%M%S.%f}-jaynes_demo"
  remote_tar: "{secret.JYNS_HOME}/jaynes-demo/{now:%Y-%m-%d}/{now:%H%M%S.%f}-jaynes_demo.tar"
  pypath: true
  excludes: >-
    --exclude='data' --exclude='samples' --exclude='images' --exclude='videos'
    --exclude='figures' --exclude='results' --exclude='analysis' --exclude='*.ipynb'
    --exclude='*__pycache__' --exclude='*.git' --exclude='*.png' --exclude='*.gif'
    --exclude='*.mp4' --exclude='*.idea' --exclude='*.egg-info' --exclude='*.pkl'
    --exclude='*.log*'
  compress: true
runners:
- !runners.Tmux &tmux_runner
  name: "jaynes-demo-{now:%H%M%S.%f}-{RUN.count}"
  startup: >
    source $HOME/.jaynes_bash;
    conda activate torch;
    echo running inside `hostname`;
  envs: >
    LANG=utf-8
    LC_CTYPE=en_US.UTF-8
  pypath: "{mounts[0].host_path}"
  work_dir: "{mounts[0].host_path}"
  exit_session_when_done: true
  post_script: "tmux list-sessions"
run:
  mounts:
  - *code_mount
  runner: *tmux_runner
  launch: !ENV
    type: ssh
    ip: "{secret.JYNS_HOST}"
    username: "{secret.JYNS_USERNAME}"
    password: "{secret.JYNS_PASSWORD}"
    launch_dir: "{secret.JYNS_HOME}/jaynes-demo/{now:%Y-%m-%d}/{now:%H%M%S.%f}"
    # pem: "{secret.JYNS_PEM}"
