version: 0
run:
  mounts:
    - !mounts.TarMount
      local_path: .
      local_tar: /tmp/{now:%Y-%m-%d}/{now:%H%M%S.%f}-decision-transformer.tar
      host_path: "{secret.MOUNT_DIR}/{now:%Y-%m-%d}/{now:%H%M%S.%f}/decision-transformer"
      remote_tar: "{secret.MOUNT_DIR}/{now:%Y-%m-%d}/{now:%H%M%S.%f}/decision-transformer.tar"
      pypath: true
      excludes: >-
        --exclude='data' --exclude='samples' --exclude='images' --exclude='videos'
        --exclude='figures' --exclude='results' --exclude='analysis' --exclude='*.ipynb'
        --exclude='*__pycache__' --exclude='*.git' --exclude='*.png' --exclude='*.gif'
        --exclude='*.mp4' --exclude='*.idea' --exclude='*.egg-info' --exclude='*.pkl'
        --exclude='*.log*' --exclude='custom_vendor' --exclude='*.csv'
        --exclude='checkpoints' --exclude='log'
      compress: true
  runner: !runners.Slurm
    # these should go into your ~/.bashrc, so that you can remove these
    envs: >-
      LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 LANGUAGE=en_US
    # startup: >-
    # module load python/3.8.5-fasrc01 cuda/11.0.3-fasrc01 cudnn/8.0.4.30_cuda11.1-fasrc01 Anaconda3/2020.11
    shell: ./srun-singularity.sh singularity/model-free_latest.sif
    job_name: "jaynes-demo-$RANDOM"
    pypath: "{mounts[0].host_path}"
    work_dir: "{mounts[0].host_path}"
    # exclude: d-7-11-2,d-10-1-2
    # time_limit: "0:0:20"
    partition: gpu
    mem: 10000
    n_cpu: 8
    n_gpu: 1
  launch: !ENV
    type: manager
    host: "{secret.LOGIN_NODE}"
    token: "{secret.USERNAME}"
    launch_dir: "{secret.WORK_DIR}/jaynes-mounts/jaynes_demo/{now:%Y-%m-%d}/{now:%H%M%S.%f}"
    timeout: 5
