version: 0
run:
  mounts:
    - !mounts.SSHCode
      local_path: .
      local_tar: /tmp/{now:%Y-%m-%d}/{now:%H%M%S.%f}-decision-transformer.tar
      host_path: "{env.JYNS_SLURM_DIR}/{now:%Y-%m-%d}/{now:%H%M%S.%f}/decision-transformer"
      remote_tar: "{env.JYNS_SLURM_DIR}/{now:%Y-%m-%d}/{now:%H%M%S.%f}/decision-transformer.tar"
      pypath: true
      excludes: >-
        --exclude='data' --exclude='samples' --exclude='images' --exclude='videos'
        --exclude='figures' --exclude='results' --exclude='analysis' --exclude='*.ipynb'
        --exclude='*__pycache__' --exclude='*.git' --exclude='*.png' --exclude='*.gif'
        --exclude='*.mp4' --exclude='*.idea' --exclude='*.egg-info' --exclude='*.pkl'
        --exclude='*.log*' --exclude='custom_vendor' --exclude='*.csv'
        --exclude='checkpoints' --exclude='log'
      compress: true
  runner: !runners.Slurm
    # these should go into your ~/.bashrc, so that you can remove these
    envs: >-
      LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 LANGUAGE=en_US
      LD_LIBRARY_PATH=$HOME/.mujoco/mujoco210/bin:$LD_LIBRARY_PATH
      MJLIB_PATH=$HOME/.mujoco/mujoco-2.1.1/lib/libmujoco.so
      PYTHONPATH=$PYTHONPATH:/state/partition1/user/$USER/mujoco-py
      MUJOCO_GL=egl
      C_INCLUDE_PATH=$C_INCLUDE_PATH:$HOME/vendor/glew/include
      LD_PRELOAD=$HOME/vendor/glew/lib/libGLEW.so.2.2.0:/usr/lib/x86_64-linux-gnu/libEGL.so
    setup: |
      source /etc/profile.d/modules.sh
      source $HOME/.bashrc
      module load cuda/10.2
      module load anaconda/2021b
      module load mpi/openmpi-4.0
      source $HOME/proxy.sh
    startup: >-
      echo "copying mujoco-py";
      mkdir -p /state/partition1/user/$USER;
      cp -r /home/gridsan/$USER/mujoco-py /state/partition1/user/$USER/;
      echo "finished";
      export MUJOCO_GL=egl;
      export CUDA_VISIBLE_DEVICES=0;
    pypath: "{mounts[0].host_path}"
    work_dir: "{mounts[0].host_path}"
    # exclude: d-7-11-2,d-10-1-2
    # time_limit: "0:0:20"
    mem: 10000
    n_cpu: 8
    n_gpu: volta:1
  launch: !ENV
    type: ssh
    ip: "{env.JYNS_SLURM_HOST}"
    username: "{env.JYNS_USERNAME}"
    pem: "{env.JYNS_SLURM_PEM}"
