version: 0
run:
  mounts:
  - !mounts.GSCode
    prefix: "gs://{env.JYNS_GS_BUCKET}/jaynes-debug"
    local_path: .
    host_path: "$HOME/jaynes-mounts/{now:%Y-%m-%d}/{now:%H%M%S.%f}/code-mount"
    pypath: true
    excludes: >-
      --exclude='*__pycache__' --exclude='*.git' --exclude='*.idea' --exclude='*.egg-info'
      --exclude='*.pkl'
    compress: true
  - !mounts.GSCode
    prefix: "gs://{env.JYNS_GS_BUCKET}/.gce"
    local_path: "$HOME/.gce"
    host_path: "$HOME/jaynes-mounts/{now:%Y-%m-%d}/{now:%H%M%S.%f}/.gce"
    file_mask: "$USER-improbable-gs-service.json"
    container_path: /root/.gce
    compress: true
  runner: !runners.Docker
    name: "jaynes-demo"  # only for docker
    image: "episodeyang/jaynes"
    # Install Docker like this.
    # setup: |
    #   sudo yum update -y
    #   sudo amazon-linux-extras install docker
    #   sudo yum install docker
    #   sudo service docker start
    #   sudo usermod -a -G docker $USER
    # docker_cmd: sudo docker
    setup: |
      chmod -R 777 $HOME/jaynes-mounts/{now:%Y-%m-%d}/{now:%H%M%S.%f}/
    startup: yes | pip install jaynes ml-logger -q
    envs: LANG=utf-8
    pypath: "{mounts[0].container_path}"
    work_dir: "{mounts[0].container_path}"
    ipc: host
  launch: !ENV
    # Needed for the S3 code mount
    setup: |
      pip install -q awscli ml-logger params-proto
    type: gce
    launch_dir: "$HOME/jaynes-mounts"
    project_id: "{env.JYNS_GCP_PROJECT}"
    zone: europe-west4-b
    image_project: deeplearning-platform-release
    image_family: pytorch-latest-gpu
#    instance_type: a2-highgpu-1g
    instance_type: n1-standard-4
    accelerator_type: nvidia-tesla-t4
    accelerator_count: 1
    preemptible: true
    terminate_after: true
    tags:
      install-nvidia-driver: True


