version: 0
verbose: true
run:
  mounts:
    - !mounts.S3Code
      prefix: "s3://{env.JYNS_AWS_S3_BUCKET}/jaynes-debug"
      local_path: .
      host_path: "/home/ubuntu/jaynes-mounts/{now:%Y-%m-%d}/{now:%H%M%S.%f}"
      pypath: true
      excludes: >-
        --exclude='*__pycache__' --exclude='*.git' --exclude='*.idea' --exclude='*.egg-info'
        --exclude='*.pkl'
      compress: true
  runner: !runners.Docker
    name: "jaynes-docker-demo-{now:%H%M%S}-{RUN.count}"
    image: "episodeyang/jaynes"
    # Install Docker like this.
    # setup: |
    #   sudo yum update -y
    #   sudo amazon-linux-extras install docker
    #   sudo yum install docker
    #   sudo service docker start
    #   sudo usermod -a -G docker $USER
    # docker_cmd: sudo docker
    startup: yes | pip install jaynes ml-logger -q
    envs: LANG=utf-8
    pypath: "{mounts[0].container_path}"
    workdir: "{mounts[0].container_path}"
    ipc: host
  launch: !ENV
    # use AWS_PROFILE to select the access key and access .secret.
    # post a feature request under issues, if you want more ways to customize this.
    type: ec2
    launch_dir: /home/ec2-user/jaynes-mounts

    # These are usually updated as a group
    region: us-east-1
    availability_zone: us-east-1a
    image_id: ami-0c5f0a577c97b13a8
    key_name: ge-us-east-1
    iam_instance_profile_arn: "{env.JYNS_AWS_INSTANCE_PROFILE}"
    security_group: ge-jaynes-sg
    instance_type: g4dn.4xlarge
    spot_price: 0.4
    terminate_after: true
