apiVersion: v1
kind: Pod
metadata:
  name: ge-test-job
spec:
    containers:
    - name: ge-test-1
      image: improbableailab/model-free
      command: ["perl", "-Mbignum=bpi", "-wle", "print 1"]
      resources:
        limits:
          memory: 200Mi
          cpu: 1000m
        requests:
          memory: 50Mi
          cpu: 500m
      volumeMounts:
      - mountPath: /jaynes-mounts
        name: ge-pvc
    restartPolicy: Never
    volumes:
      - name: ge-pvc
        persistentVolumeClaim:
          claimName: ge-pvc
