apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaynes-mounts-volume
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
